<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="ATAS.Strategies">
			<HintPath>"C:\Program Files (x86)\ATAS Platform\ATAS.Strategies.dll"</HintPath>
			<Private>false</Private>
		</Reference>

		<Reference Include="ATAS.Indicators">
			<HintPath>C:\Program Files (x86)\ATAS Platform\ATAS.Indicators.dll</HintPath>
			<Private>false</Private>
		</Reference>

		<Reference Include="ATAS.Indicators.Technical">
			<HintPath>C:\Program Files (x86)\ATAS Platform\ATAS.Indicators.Technical.dll</HintPath>
			<Private>false</Private>
		</Reference>

		<Reference Include="Utils.Common">
			<HintPath>C:\Program Files (x86)\ATAS Platform\Utils.Common.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>
